const images = []

images['CRO1'] = ''
images['CRO2'] = ''
images['CRO3'] = ''
images['CRO4'] = ''
images['CRO5'] = ''
images['CRO6'] = ''
images['CRO7'] = ''
images['CRO8'] = ''
images['CRO9'] = ''
images['CRO10'] = ''
images['CRO11'] = ''
images['CRO12'] = ''
images['CRO13'] = 'QmdzhK28Uama6xJstZZbTRh8RPT2dbT4dBoxjdAaC6gN7N'
images['CRO14'] = ''
images['CRO15'] = ''
images['CRO16'] = ''
images['CRO17'] = ''
images['CRO18'] = ''
images['CRO19'] = ''
images['CRO20'] = ''
images['CRO21'] = ''
images['CRO22'] = ''
images['CRO23'] = ''
images['CRO24'] = ''
images['CRO25'] = ''
images['CRO26'] = ''
images['CRO27'] = ''
images['CRO28'] = ''
images['CRO29'] = ''
images['CRO30'] = ''

module.exports = exports = images