name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v22.12.0
        uses: actions/setup-node@v3
        with:
          node-version: v22.12.0
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - run: npm test